import type { IEnumDescriptorProto } from 'protobufjs/ext/descriptor/index.js';
import { DescriptorModel } from '../model/descriptor-model.js';
import { TYPE_ENUM, TYPE_MESSAGE } from '../model/types.js';
import type {
  FileModel,
  PluginOptions,
  TypeSymbol
} from '../model/types.js';
import {
  relativeModule,
  requireArkIdentifier,
  stripProtoExtension,
  toUpperCamel
} from '../naming.js';
import { ArkTSMessageRenderer } from './message-renderer.js';

const PLUGIN_VERSION = '0.4.0';

/**
 * 持有单文件渲染上下文，负责 import 规划和顶层声明组装。
 */
export class ArkTSFileRenderer {
  private readonly imports: Map<string, string>;
  private readonly currentOutput: string;

  public constructor(
    private readonly file: FileModel,
    private readonly model: DescriptorModel,
    private readonly options: PluginOptions
  ) {
    this.currentOutput = model.requireOutputName(file, file.fileName);
    this.imports = this.collectImports();
  }

  public render(): string {
    const declarations: string[] = [];
    for (const symbol of this.file.symbols) {
      if (symbol.kind === 'enum') {
        declarations.push(renderEnum(symbol.arkName, symbol.enum));
      } else if (symbol.kind === 'message') {
        declarations.push(
          new ArkTSMessageRenderer(symbol, this.file, this.model, this.imports).render()
        );
      }
    }

    return (
      [
        '// Generated by protoc-gen-arkts. DO NOT EDIT.',
        `// Plugin version: ${PLUGIN_VERSION}`,
        this.renderImports(),
        declarations.join('\n\n')
      ].join('\n\n') + '\n'
    );
  }

  private renderImports(): string {
    // runtime_import 以 "." 开头时相对于输出根目录，否则按 HarmonyOS 模块名原样使用。
    const runtimeImport: string = this.options.runtimeImport.startsWith('.')
      ? relativeModule(this.currentOutput, this.options.runtimeImport)
      : this.options.runtimeImport;

    const importLines: string[] = [
      `import { collections } from '@kit.ArkTS';`,
      `import { ProtoReader, ProtoWireType, ProtoWriter, appendProtoValue, getProtoMapKeys, getProtoMapValue, setProtoMapValue } from '${runtimeImport}';`
    ];

    const groupedImports: Map<string, Array<[string, string]>> = new Map();
    for (const [fullName, alias] of this.imports) {
      const symbol: TypeSymbol = this.model.requireSymbol(fullName, this.file.fileName);
      const items: Array<[string, string]> = groupedImports.get(symbol.fileName) ?? [];
      items.push([symbol.arkName, alias]);
      groupedImports.set(symbol.fileName, items);
    }

    for (const sourceFile of [...groupedImports.keys()].sort()) {
      const source: FileModel = this.model.requireFile(
        sourceFile,
        `${this.file.fileName}: import of ${sourceFile}`
      );

      const specifiers: string = (groupedImports.get(sourceFile) ?? [])
        .sort((left, right): number => left[1].localeCompare(right[1]))
        .map(([name, alias]): string => (name === alias ? name : `${name} as ${alias}`))
        .join(', ');

      const sourceOutput: string = this.model.requireOutputName(
        source,
        `${this.file.fileName}: import of ${sourceFile}`
      );

      importLines.push(
        `import { ${specifiers} } from '${relativeModule(this.currentOutput, sourceOutput)}';`
      );
    }
    return importLines.join('\n');
  }

  /**
   * 收集当前文件引用的外部类型，并为名称冲突的类型生成稳定别名。
   */
  private collectImports(): Map<string, string> {
    const referenced: Set<string> = new Set();
    for (const symbol of this.file.symbols) {
      if (symbol.kind === 'enum') {
        continue;
      }

      for (const field of symbol.message.field ?? []) {
        if ((field.type === TYPE_MESSAGE || field.type === TYPE_ENUM) && field.typeName) {
          const target: TypeSymbol = this.model.requireSymbol(
            field.typeName,
            `${this.file.fileName}: field ${field.name ?? '<unnamed>'}`
          );
          if (target.fileName !== this.file.fileName) {
            referenced.add(target.fullName);
          }
        }
      }
    }

    const usedNames: Set<string> = new Set(
      this.file.symbols.map((symbol): string => symbol.arkName)
    );

    const imports: Map<string, string> = new Map();
    for (const fullName of [...referenced].sort()) {
      const symbol: TypeSymbol = this.model.requireSymbol(fullName, this.file.fileName);
      let alias: string = symbol.arkName;
      if (usedNames.has(alias)) {
        alias = toUpperCamel(`${stripProtoExtension(symbol.fileName)}.${fullName.slice(1)}`);
      }
      if (usedNames.has(alias)) {
        throw new Error(`${this.file.fileName}: imported ArkTS alias ${alias} conflicts for ${fullName}`);
      }
      usedNames.add(alias);
      imports.set(fullName, alias);
    }
    return imports;
  }

}

function renderEnum(name: string, enumDescriptor: IEnumDescriptorProto): string {
  const members: string = (enumDescriptor.value ?? [])
    .map((value): string => `  ${requireArkIdentifier(value.name, `enum ${name} value`)} = ${value.number ?? 0}`)
    .join(',\n');
  return `export enum ${name} {\n${members}\n}`;
}
